name: Ejecutando CI Pipeline en Jenkins

on:
  push:
    branches:
      - master

jobs:
  jenkins_job:
    runs-on: ubuntu-latest

    steps:
      - name: Invocando a Jenkins
        id: jenkins
        run: |
          curl -X POST "http://ec2-23-22-162-149.compute-1.amazonaws.com:8080/job/ci-build-service/buildWithParameters?service_name=orders-service&delay=0sec" --user "admin:11e5dc717eb1a0d1d7481aaa1b8c14754f"

      - name: Progreso
        run: |
          echo "Esperando a finalizar el piepline..."
          while true; do
            job_status=$(curl -s "http://ec2-23-22-162-149.compute-1.amazonaws.com:8080/job/ci-build-service/lastBuild/api/json" \
              --user "admin:11e5dc717eb1a0d1d7481aaa1b8c14754f" \
              | jq -r '.result')
            if  [[ $job_status == "SUCCESS" || $job_status != "null" ]]; 
              then
                echo "El job ha finalizado correctamente"
                break
              else
                echo "Job error: $job_status"
                exit 2
            fi
            sleep 10
          done
