name: Ejecutando CI Pipeline en Jenkins

on:
  push:
    branches:
      - master

jobs:
  jenkins_job:
    runs-on: ubuntu-latest

    steps:
      - name: Invocando a Jenkins
        id: jenkins
        run: |
          curl -X POST "http://ec2-23-22-162-149.compute-1.amazonaws.com:8080/job/ci-build-service/buildWithParameters?service_name=orders-service&delay=0sec" \
          --user "admin:11e5dc717eb1a0d1d7481aaa1b8c14754f" \
          --data-urlencode'

      - name: Progreso
        run: |
          echo "Esperando a finalizar el piepline..."
          while true; do
            job_status=$(curl -s "http://ec2-23-22-162-149.compute-1.amazonaws.com:8080/job/ci-build-service/lastBuild/api/json" \
              --user "admin:11e5dc717eb1a0d1d7481aaa1b8c14754f" \
              | jq -r '.result')
            if [[ $job_status == "SUCCESS" || $job_status == "FAILURE" || $job_status == "ABORTED" ]]; then
              echo "El job ha finalizado con estado: $job_status"
              break
            fi
            sleep 10
          done
