name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://ec2-44-203-186-42.compute-1.amazonaws.com:8080"
        user: "git-user"
        token: ${{ secrets.TOKEN }}
        job: "build-orders-service"
